Java SDK Test Harness bug fixes
DevCycleHQ/java-server-sdk pull request #42
Opened 2023-02-09 23:20 UTC by kaushalkapasi

2023-02-09 23:20 UTC, kaushalkapasi commented
Current dependencies on/for this PR:
* main
  * **PR #42** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/java-server-sdk/42" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #43** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/java-server-sdk/43" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #44** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/java-server-sdk/44" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #45** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/java-server-sdk/45" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/DevCycleHQ/java-server-sdk/42?utm_source=stack-comment).

2023-03-01 19:28 UTC, suthar26 commented on src/main/java/com/devcycle/sdk/server/cloud/api/DVCCloudClient.java
> +      System.out.println("get exception");
should these debug logs be removed?

2023-03-01 19:33 UTC, suthar26 requested changes

2023-03-01 19:33 UTC, suthar26 commented on src/main/java/com/devcycle/sdk/server/common/model/Variable.java
> +    public static TypeEnum fromClass(Class<?> clazz) {
clazz, intentional typo?

2023-03-01 19:36 UTC, suthar26 approved these changes

2023-03-01 22:15 UTC, merged